### ISSUE TITLE
User-Friendly Settings UI

### ISSUE THREAD

**Issue by dsnvwlmnt** [JusKillmeQik/PoE-Leveling-Guide#43]
If you're going for wide adoption, all that's missing is to move the settings from manual text files to a popup window, similar to other such tools.

For e.g. whenever it's launched, you'd select the build you want from a dropdown list of ones you have locally (or better yet, pulled from your Zizaran/etc. master list in the cloud? :), and that's it you're done. No messing around in text files, which, let's be real, regular users have no inclination in dealing with.

**Comment by JusKillmeQik** [comment]
Friendly settings menu created, including a gem editor. Default builds can just be selected with no modifications to any text files.

fixed in: ab6597b89ab000b125acf8f852b8aba5cf654c07
