### ISSUE TITLE
"Exiting Script" When I try to run it

### ISSUE THREAD

**Issue by AmbivalentX** [JusKillmeQik/PoE-Leveling-Guide#44]
I had the guide running but I closed it in order to change my Gems, now that I have done that I tried to reload the script, and now it just says "Exiting Script." when I try to launch it.

**Comment by JusKillmeQik** [comment]
copy your json file into this website: https://jsoneditoronline.org/

It will show you where your mistake is so the script will load again

**Comment by victorpatton** [comment]
remove this block of text from line 130 save and it works:

    If (not gem_data.levels.Length()) {
        MsgBox, 16, , Error reading gem data! `n`nExiting script.
        ExitApp
    }
} Catch e {
    MsgBox, 16, , % e "`n`nExiting script."
    ExitApp
}

**Comment by AmbivalentX** [comment]
Awesome, it's running again, thank you!
