### ISSUE TITLE
Doesn't Support Some Multi-Monitor Setups Gracefully

### ISSUE THREAD

**Issue by dsnvwlmnt** [JusKillmeQik/PoE-Leveling-Guide#47]
I have a different monitor setup this season and I was never able to get this overlay to behave the way I wanted, even messing around editing the code.

My setup is shown below. I have PoE on monitor 2, but no matter what I did, most of the overlay would only ever show on monitor 1. That wouldn't be the end of the world, if it weren't for the fact that any time I wanted to manually change the Act #, I'd have to move the mouse out of the PoE window up to monitor 1, which would make the overlay disappear (because the PoE window is no longer active). Kind of infuriating haha.

![image](https://user-images.githubusercontent.com/14173022/78420194-d17e9480-7601-11ea-95a8-ac8adea2a4de.png)

**Comment by JusKillmeQik** [comment]
Can you try setting your levelYoffset to 1.955 and see if the experience tracker moves to the correct screen? If it does, I'll add Y offsets for the other elements so you can move them down a screen.

**Comment by dsnvwlmnt** [comment]
I tested setting gemsYoffset to 1.180 and it does appear on monitor 2 (though cut off a bit, since it's on the left side and the resolution of monitor 2 is not as wide as monitor 1). [I "disabled" exp tracker at some point but don't remember how, I think maybe by setting levelXoffset to 1, so it's simply off the screen.]

**Comment by JusKillmeQik** [comment]
All of the elements can now have their X and Y variables configured in the settings menu. So you could change the offset to above 1 or below 0 to move it to different screens. Let me know how it works.
