### ISSUE TITLE
UI flickers and then hides?

### ISSUE THREAD

**Issue by matthewedogawa** [JusKillmeQik/PoE-Leveling-Guide#49]
maybe I read something wrong but the UI for notes doesn't stay open in zones

**Comment by Olorun** [comment]
Are you using Vulkan as the renderer? If so, try changing to DirectX11 and see if that works.

**Comment by JusKillmeQik** [comment]
Yeah, PoE's vulkan renderer is in beta and has broken every AutoHotKey program. There are a few forum posts about. I'm keeping an eye on this and if a fix becomes available that I can implement I will. For now though, I think you'll just have to use DirectX until they update their renderer.

**Comment by Piefayth** [comment]
I actually have this problem even on the DX renderer.

**Comment by JusKillmeQik** [comment]
Does everything flicker or just the notes? Can you try setting the Display Timeout in the settings to 0 and see if the problem goes away?

**Comment by Piefayth** [comment]
Oh, yep. Figured there must've been an option I was overlooking. Thanks for the super quick response.

**Comment by JusKillmeQik** [comment]
I have added Vulkan Support. Please download the newest version and make sure PoE is in "Windowed" mode not "Windowed Fullscreen". My tool will put it back in Fullscreen but with the Overlay still visible.
