### ISSUE TITLE
Automatic detection not working

### ISSUE THREAD

**Issue by Olorun** [JusKillmeQik/PoE-Leveling-Guide#50]
Even when trying to run with administrator mode, none of the images/notes show up. When I press reload, I see the notes for a second, but nothing shows up ingame.
Not sure if it matters, but I'm using the Korean client:
C:\Daum Games\Path of Exile\PathOfExile_x64_KG.exe
which gets launched directly by starting it on https://poe.game.daum.net/

**Comment by Olorun** [comment]
Okaay, problem identified - I've been using Vulkan as a renderer. Once I changed it to DirectX11, the display was working again.

**Comment by Olorun** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/1149
Seems like a bug native to AHK w/ Vulkan

**Comment by JusKillmeQik** [comment]
Yeah, I'm keeping an eye on this. If a fix becomes available on my end I'll update it right away. But I think we have to wait for GGG to update their Vulkan renderer.

**Comment by JusKillmeQik** [comment]
I have added Vulkan Support. Please download the newest version and make sure PoE is in "Windowed" mode not "Windowed Fullscreen". My tool will put it back in Fullscreen but with the Overlay still visible.
