### ISSUE TITLE
Text and Overlay Dissappears

### ISSUE THREAD

**Issue by Hagibiss** [JusKillmeQik/PoE-Leveling-Guide#53]
I load it up and its in the correct mode, but after a few seconds the text disappears. Not sure what is happening as I am following the posted steps correctly.

**Comment by JusKillmeQik** [comment]
The text automatically disappears after 5 seconds to make it easier to see the game. You can hit F10 to open settings and change the Display Timeout to 0 if you don't want anything to disappear. You could instead set Persist Text to True. This will leave the text, but allow the controls to disappear so you can see Gem Names while leveling (they show up at the top of the screen). If you do set the Timeout to 0, just press Alt+F1 to manually hide the text when you need to read something on the screen.

Let me know if that fixes your issue.

**Comment by Hagibiss** [comment]
That makes sense thank you so much - it seemed like it was intentional, but I couldn't find the setting to switch. Really great tool just improved my Act 1 by like 50%.

**Comment by JusKillmeQik** [comment]
Glad to hear it, see you in Maps!
