### ISSUE TITLE
Have no "Releases" page

### ISSUE THREAD

**Issue by Byngalo** [JusKillmeQik/PoE-Leveling-Guide#54]
https://github.com/JusKillmeQik/PoE-Leveling-Guide/releases
Add your program here pls, i see only download link on reddit...

**Comment by rtyner** [comment]
Just download from the main repo page.

**Comment by LillieSatou** [comment]
What if files change? We won't be getting notifications of said thing unless we do more than just a normal "watch <> tracker," which quite a lot of people don't want.

**Comment by JusKillmeQik** [comment]
I have created a release for the new Heist Gems and will create releases for major updates moving forward. Thank you for the suggestion.
