### ISSUE TITLE
Better/different file management

### ISSUE THREAD

**Issue by charsz** [JusKillmeQik/PoE-Leveling-Guide#61]
Hi,

more feature request than Issue. I think it would be much easier to maintain multiple guides (kudos for including them already in the code) if they won't be spread over multiple files. I think one file per act, or even two files at whole would make it much easier. 
By two files I mean one file with guide for all acts and one file with tips per zone. 
I know that would require a lot of code changes but may be considered.

**Comment by JusKillmeQik** [comment]
completed in the 4.0 release
