### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by xnopain1** [JusKillmeQik/PoE-Leveling-Guide#68]
THe script start and after 1s the pop up in game closes and the hotkeys dont work help me.

**Comment by JusKillmeQik** [comment]
If you're running the Epic launcher or KakaoClient, I pushed fixes for that yesterday. Please redownload from here: https://github.com/JusKillmeQik/PoE-Leveling-Guide/archive/master.zip

If that's not your problem, please join our Discord and ask for help: https://discord.gg/fzHj3BT
