### ISSUE TITLE
Sometimes auto detects zone and sometimes doesn't

### ISSUE THREAD

**Issue by WobblePotato** [JusKillmeQik/PoE-Leveling-Guide#70]
Weird cause it sometimes swaps automatically and sometimes doesn't. Not sure why. I opened up client.txt, it did show that I loaded into a new area, but didn't update. I know its a zone with a config too, not like a weird zone that doesn't have the guide ready. *shrug*

**Comment by JusKillmeQik** [comment]
Is it for specific zones? If you leave that zone and go back in, does it work? Do you have DND mode on? Did you get any other logs immediately after entering the zone? I only read one log line at a time, so sometimes if there are multiple logs I'll miss a zone change. I've ignored DND logs in my latest patch, but if you see other logs that interfere I'd be happy to debug this problem.

**Comment by WobblePotato** [comment]
I'll try and notice the next time I get this problem, but for now i'm done levelling. Thanks for responding! I was on DND yeah, think I only saw DND message and entering zone message in the log.

**Comment by JusKillmeQik** [comment]
If other people are having this issue, please also try downloading the standalone client.
