### ISSUE TITLE
Add Witch/Elementalist flame wall spell slinger (anyone have a working version?)

### ISSUE THREAD

**Issue by emirkmo** [JusKillmeQik/PoE-Leveling-Guide#74]
Hey, I want to add elementalist flame wall spell slinger build, which I think is going to be a very popular league start. But I wanted to open up an issue in case someone else had a working version already they could share so I don’t do extra work for nothing.

**Comment by JusKillmeQik** [comment]
I don't think anyone is working on this. I recommend checking out our Discord server and asking there in the "share-builds" channel. If you finish the build before Tuesday so I can review it, I will make it part of this release.
