### ISSUE TITLE
Align notes and guides blocks

### ISSUE THREAD

**Issue by Cry0nicS** [JusKillmeQik/PoE-Leveling-Guide#81]
Looks a bit annoying that the text area for the guides is dynamically adjusted, but the headers are not.

![image](https://user-images.githubusercontent.com/29982205/114870094-7086c080-9e00-11eb-8365-742cba0a73eb.png)

Adjusted, it should look like this (ignore my paint skills)
![image](https://user-images.githubusercontent.com/29982205/114870595-06225000-9e01-11eb-9a74-4b0ecdc7d620.png)

**Comment by JusKillmeQik** [comment]
The intention was to actually make everything smaller to save screen space. You can now see boss names and gem names easier since they go where the headers used to. I think less is more here, but I'll leave this issue open to consider it longer and take more feedback.

**Comment by JusKillmeQik** [comment]
I didn't get any more feedback and like the way it looks currently. Closing this for now.
