### ISSUE TITLE
Not working anymore (hotkeys and map layouts)

### ISSUE THREAD

**Issue by jumbledlearner** [JusKillmeQik/PoE-Leveling-Guide#87]
For some reason the hotkeys do nothing for me, meaning the map layouts don't load, and I can no longer bring up/hide different menus. Sometimes it works, sometimes it doesn't upon restarting the program multiple times, very peculiar.

**Comment by JusKillmeQik** [comment]
This generally means it doesn't have admin access. Try running as an admin user and see if that helps. If not, check out the discord for more advice.
