### ISSUE TITLE
Pictures are not working properly if they are not attached to notes

### ISSUE THREAD

**Issue by norecha** [JusKillmeQik/PoE-Leveling-Guide#88]
![image](https://user-images.githubusercontent.com/10354246/122156837-cba45600-ce37-11eb-9e1f-06c598513fb6.png)

If Pic X coordinate is anything > 0, multi pics are stacked on top of each other. I want to put the notes to left and pictures to middle

**Comment by JusKillmeQik** [comment]
Fixed in e07b1b7
