### ISSUE TITLE
Single Digit Level Detection not working

### ISSUE THREAD

**Issue by NFlieger** [JusKillmeQik/PoE-Leveling-Guide#94]
![bug in gif](https://i.imgur.com/p1sq2MA.gif)

It seems like the level detection for the gem setup does not work below level 10.
You can see, that he registered the new log line, because he is reloading the gem setup. However if you are below level 10, he will always display the level 02 gem setup.

It does not work if i level normaly or buy testing it in local chat.

I don't seem to be the only one (would be surprising using AHK anyway), since it got already reported and ignored:
https://www.reddit.com/r/pathofexile/comments/qblmjk/comment/hhbsf56/?utm_source=share&utm_medium=web2x&context=3

**Comment by JusKillmeQik** [comment]
I think I fixed this, can you confirm if you're still having the problem so I can look into it. It's working for me, so I cannot debug unless I can replicate it.
